📁 voice-marketing-panel/
├── public/
│   └── index.html ✅
├── src/
│   ├── App.jsx ✅
│   ├── main.jsx ✅
│   ├── VoiceMarketingPanel.jsx ✅ ← şu anda elinde olan dosya
│   └── index.css ✅
├── package.json ✅
